---

- name: Deploy EDA
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    apply: yes
    definition: "{{ lookup('template', 'eda_object.yml.j2') }}"
    wait: true
    wait_condition:
      type: "Running"
      status: "True"

- name: Remove ownerReferences to prevent garbage collection of new EDA CRO
  kubernetes.core.k8s:
    definition:
      apiVersion: '{{ api_version }}'
      kind: EDA
      metadata:
        name: '{{ deployment_name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
